export interface Game {
  id: string;
  name: string;
  description: string;
  defaultPort: number;
  steamAppId?: number;
  image?: string;
}

// Full catalogue from https://linuxgsm.com/servers/ (as of 2024)
export const GAMES_CATALOG: Game[] = [
  { id: "7d2d", name: "7 Days to Die", description: "Zombie survival horror", defaultPort: 26900, steamAppId: 251570 },
  { id: "aa", name: "Angry Animals", description: "Mod for Minecraft", defaultPort: 25565 },
  { id: "arma2", name: "Arma 2", description: "Military tactical shooter", defaultPort: 2302 },
  { id: "arma3", name: "Arma 3", description: "Military tactical shooter", defaultPort: 2302 },
  { id: "arma4", name: "Arma 4", description: "Upcoming military tactical shooter", defaultPort: 2302 },
  { id: "ark", name: "ARK: Survival Evolved", description: "Dinosaur survival MMO", defaultPort: 27015, steamAppId: 346110 },
  { id: "atlas", name: "ATLAS", description: "Open world pirate adventure", defaultPort: 33377 },
  { id: "battalion1944", name: "Battalion 1944", description: "WWII shooter", defaultPort: 7777 },
  { id: "bdo", name: "Black Desert Online", description: "MMORPG", defaultPort: 7777 },
  { id: "bf1942", name: "Battlefield 1942", description: "Classic FPS", defaultPort: 14567 },
  { id: "bf2", name: "Battlefield 2", description: "Classic FPS", defaultPort: 16567 },
  { id: "bfv", name: "Battlefield Vietnam", description: "Vietnam era FPS", defaultPort: 15567 },
  { id: "callofduty", name: "Call of Duty", description: "Various CoD games", defaultPort: 28960 },
  { id: "colonysurvival", name: "Colony Survival", description: "Survival/building", defaultPort: 27015 },
  { id: "conanexiles", name: "Conan Exiles", description: "Survival in Conan's world", defaultPort: 7777, steamAppId: 440900 },
  { id: "cs16", name: "Counter-Strike 1.6", description: "Classic CS", defaultPort: 27015 },
  { id: "cscz", name: "Counter-Strike: Condition Zero", description: "CS with singleplayer", defaultPort: 27015 },
  { id: "cs2", name: "Counter-Strike 2", description: "Modern competitive FPS", defaultPort: 27015, steamAppId: 730 },
  { id: "daysofwar", name: "Days of War", description: "WWII shooter", defaultPort: 27015 },
  { id: "dayz", name: "DayZ", description: "Zombie survival", defaultPort: 2302, steamAppId: 221100 },
  { id: "deadmatter", name: "Dead Matter", description: "Zombie survival", defaultPort: 27015 },
  { id: "diabotical", name: "Diabotical", description: "Arena FPS", defaultPort: 30000 },
  { id: "dod", name: "Day of Defeat", description: "WWII teamplay", defaultPort: 27015 },
  { id: "dods", name: "Day of Defeat: Source", description: "Source engine DoD", defaultPort: 27015 },
  { id: "dom4", name: "Dominions 4", description: "Fantasy strategy", defaultPort: 31330 },
  { id: "dom5", name: "Dominions 5", description: "Fantasy strategy", defaultPort: 31330 },
  { id: "eco", name: "Eco", description: "Economy/survival", defaultPort: 3000 },
  { id: "factorio", name: "Factorio", description: "Factory building", defaultPort: 34197, steamAppId: 427520 },
  { id: "fivem", name: "FiveM", description: "GTA V multiplayer", defaultPort: 30120 },
  { id: "fortressforever", name: "Fortress Forever", description: "Team Fortress mod", defaultPort: 27015 },
  { id: "frostpunk", name: "Frostpunk", description: "City survival", defaultPort: 27015 },
  { id: "growing", name: "The Growing", description: "Social survival", defaultPort: 7777 },
  { id: "gmod", name: "Garry's Mod", description: "Sandbox physics", defaultPort: 27015, steamAppId: 4000 },
  { id: "halfdeath", name: "Half Death", description: "Zombie mod", defaultPort: 27015 },
  { id: "hldm", name: "Half-Life Deathmatch", description: "Classic FPS", defaultPort: 27015 },
  { id: "hlds", name: "Half-Life Dedicated Server", description: "Classic HL server", defaultPort: 27015 },
  { id: "hlxdm", name: "Half-Life: Xen DM", description: "Half-Life expansion", defaultPort: 27015 },
  { id: "insurgency", name: "Insurgency", description: "Tactical shooter", defaultPort: 27015, steamAppId: 237410 },
  { id: "jainzcraft", name: "JainzCraft", description: "Minecraft modpack", defaultPort: 25565 },
  { id: "kag", name: "King Arthur's Gold", description: "Strategy/action", defaultPort: 54600 },
  { id: "killingfloor", name: "Killing Floor", description: "Zombie survival", defaultPort: 7708 },
  { id: "kf2", name: "Killing Floor 2", description: "Zombie survival", defaultPort: 7777, steamAppId: 232090 },
  { id: "mcb", name: "Minecraft Bedrock", description: "Minecraft Bedrock Edition", defaultPort: 19132 },
  { id: "mcpe", name: "Minecraft Pocket Edition", description: "Minecraft PE", defaultPort: 19132 },
  { id: "mcjava", name: "Minecraft Java", description: "Minecraft Java Edition", defaultPort: 25565 },
  { id: "moh", name: "Medal of Honor", description: "WWII FPS", defaultPort: 13000 },
  { id: "mtasa", name: "Multi Theft Auto: San Andreas", description: "GTA:SA multiplayer", defaultPort: 22003 },
  { id: "mumble", name: "Mumble", description: "Voice chat server", defaultPort: 64738 },
  { id: "nadeo", name: "Nadeo", description: "TrackMania", defaultPort: 2350 },
  { id: "ns2", name: "Natural Selection 2", description: "RTS/FPS hybrid", defaultPort: 27015 },
  { id: "nts", name: "No Time to Spare", description: "Action RPG", defaultPort: 27015 },
  { id: "pixark", name: "PixARK", description: "Voxel survival", defaultPort: 27015 },
  { id: "pz", name: "Project Zomboid", description: "Zombie survival", defaultPort: 16261 },
  { id: "quake", name: "Quake", description: "Classic arena FPS", defaultPort: 26000 },
  { id: "quake2", name: "Quake 2", description: "Classic arena FPS", defaultPort: 27910 },
  { id: "quake3", name: "Quake 3", description: "Classic arena FPS", defaultPort: 27960 },
  { id: "quake4", name: "Quake 4", description: "Classic arena FPS", defaultPort: 27960 },
  { id: "quakelive", name: "Quake Live", description: "Browser-based Quake", defaultPort: 27960 },
  { id: "r", name: "R Programming Language", description: "R statistical software", defaultPort: 6311 },
  { id: "ragdollkungfu", name: "Ragdoll Kung Fu", description: "Action game", defaultPort: 27015 },
  { id: "rainbow6", name: "Rainbow Six", description: "Tactical shooter", defaultPort: 7777 },
  { id: "redemption", name: "Redemption", description: "MMO", defaultPort: 7777 },
  { id: "redorchestra", name: "Red Orchestra", description: "WWII shooter", defaultPort: 7777 },
  { id: "refractor", name: "Refractor", description: "FPS engine", defaultPort: 7777 },
  { id: "risingworld", name: "Rising World", description: "Sandbox survival", defaultPort: 4300 },
  { id: "rocketleague", name: "Rocket League", description: "Car soccer", defaultPort: 7777 },
  { id: "rookkits", name: "Rook's Kits", description: "Modded Minecraft", defaultPort: 25565 },
  { id: "rust", name: "Rust", description: "Survival multiplayer", defaultPort: 28015, steamAppId: 252490 },
  { id: "satisfactory", name: "Satisfactory", description: "Factory builder", defaultPort: 7777, steamAppId: 526870 },
  { id: "sctf", name: "Sven Co-op", description: "Co-op Half-Life mod", defaultPort: 27015 },
  { id: "se", name: "Space Engineers", description: "Sandbox engineering", defaultPort: 27015, steamAppId: 297820 },
  { id: "shattered", name: "Shattered Horizon", description: "Space FPS", defaultPort: 27015 },
  { id: "sq", name: "Seabed Squad", description: "Underwater co-op", defaultPort: 27015 },
  { id: "ss3", name: "Serious Sam 3", description: "Classic FPS", defaultPort: 27015 },
  { id: "ssf", name: "StarMade", description: "Space sandbox", defaultPort: 4242 },
  { id: "stitch", name: "Stitch", description: "Adventure game", defaultPort: 27015 },
  { id: "stns", name: "Stationeers", description: "Space station sim", defaultPort: 7777, steamAppId: 643760 },
  { id: "synced", name: "Synced", description: "Rhythm shooter", defaultPort: 27015 },
  { id: "tbs", name: "The Butcher's", description: "Horror game", defaultPort: 27015 },
  { id: "teamspeak2", name: "TeamSpeak 2", description: "Voice chat", defaultPort: 5121 },
  { id: "teamspeak3", name: "TeamSpeak 3", description: "Voice chat", defaultPort: 9987 },
  { id: "terraria", name: "Terraria", description: "2D sandbox", defaultPort: 7777, steamAppId: 1286500 },
  { id: "tf2", name: "Team Fortress 2", description: "Team-based FPS", defaultPort: 27015, steamAppId: 440 },
  { id: "tfc", name: "Team Fortress Classic", description: "Original TF", defaultPort: 27015 },
  { id: "towerunite", name: "Tower Unite", description: "Social/party game", defaultPort: 27015 },
  { id: "trackmania", name: "TrackMania", description: "Racing game", defaultPort: 2350 },
  { id: "ts", name: "TeamSpeak", description: "Voice chat server", defaultPort: 9987 },
  { id: "ttt", name: "Trouble in Terrorist Town", description: "GMod gamemode", defaultPort: 27015 },
  { id: "unturned", name: "Unturned", description: "Zombie survival", defaultPort: 27015, steamAppId: 304930 },
  { id: "valheim", name: "Valheim", description: "Viking survival", defaultPort: 2456, steamAppId: 892970 },
  { id: "ventrilo", name: "Ventrilo", description: "Voice chat", defaultPort: 37893 },
  { id: "vindictus", name: "Vindictus", description: "MMORPG", defaultPort: 27015 },
  { id: "viscera", name: "Viscera Cleanup", description: "Cleaning sim", defaultPort: 7777 },
  { id: "warframe", name: "Warframe", description: "Co-op shooter", defaultPort: 2050 },
  { id: "warsow", name: "Warsow", description: "Arena FPS", defaultPort: 44400 },
  { id: "west", name: "West", description: "Wild West FPS", defaultPort: 27015 },
  { id: "wurm", name: "Wurm Online", description: "Sandbox MMO", defaultPort: 1701 },
  { id: "x3", name: "X3: Terran Conflict", description: "Space sim", defaultPort: 27015 },
  { id: "x4", name: "X4: Foundations", description: "Space sim", defaultPort: 27015 },
  { id: "zombiemaster", name: "Zombie Master", description: "Zombie mod", defaultPort: 27015 },
  { id: "zombiepanic", name: "Zombie Panic! Source", description: "Zombie survival", defaultPort: 27015 },
];
